const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      stars: 2,
      //promo: 'sale',
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/bed/bed_1.jpeg',
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/bed/bed_2.jpeg',
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_3.jpeg',
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_4.jpeg',
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/bed/bed_5.jpeg',
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/bed/bed_6.jpeg',
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_7.jpeg',
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_8.jpeg',
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_9.jpeg',
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_10.jpeg',
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_11.jpeg',
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_12.jpeg',
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_13.jpeg',
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_14.jpeg',
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_15.jpeg',
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_16.jpeg',
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_17.jpeg',
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_18.jpeg',
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_19.jpeg',
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_20.jpeg',
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_21.jpeg',
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_22.jpeg',
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_23.jpeg',
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/bed/bed_24.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-1',
      name: 'Bonaldo sheryl chair 1',
      category: 'chair',
      price: 30,
      stars: 2,
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/chair/chair_1.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-2',
      name: 'Bonaldo sheryl chair 2',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/chair/chair_2.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-3',
      name: 'Bonaldo sheryl chair 3',
      category: 'chair',
      price: 35,
      stars: 2,
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_3.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-4',
      name: 'Bonaldo sheryl chair 4',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_4.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-5',
      name: 'Bonaldo sheryl chair 5',
      category: 'chair',
      price: 30,
      stars: 2,
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/chair/chair_5.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-6',
      name: 'Bonaldo sheryl chair 6',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/chair/chair_6.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-7',
      name: 'Bonaldo sheryl chair 7',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_7.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-8',
      name: 'Bonaldo sheryl chair 8',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_8.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-9',
      name: 'Bonaldo sheryl chair 9',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_9.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-10',
      name: 'Bonaldo sheryl chair 10',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_10.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-11',
      name: 'Bonaldo sheryl chair 11',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_11.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-12',
      name: 'Bonaldo sheryl chair 12',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_12.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-13',
      name: 'Bonaldo sheryl chair 13',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_13.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-14',
      name: 'Bonaldo sheryl chair 14',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_14.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-15',
      name: 'Bonaldo sheryl chair 15',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_15.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-16',
      name: 'Bonaldo sheryl chair 16',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_16.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-17',
      name: 'Bonaldo sheryl chair 17',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_17.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-18',
      name: 'Bonaldo sheryl chair 18',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_18.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-19',
      name: 'Bonaldo sheryl chair 19',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_19.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-20',
      name: 'Bonaldo sheryl chair 20',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_20.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-21',
      name: 'Bonaldo sheryl chair 21',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_21.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-22',
      name: 'Bonaldo sheryl chair 22',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_22.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-23',
      name: 'Bonaldo sheryl chair 23',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_23.jpeg',
    },
    {
      id: 'bonaldo-sheryl-chair-24',
      name: 'Bonaldo sheryl chair 24',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/chair/chair_24.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-1',
      name: 'Chloe Sofa By Domkapa 1',
      category: 'sofa',
      price: 30,
      stars: 2,
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/sofa/sofa_1.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-2',
      name: 'Chloe Sofa By Domkapa 2',
      category: 'sofa',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/sofa/sofa_2.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-3',
      name: 'Chloe Sofa By Domkapa 3',
      category: 'sofa',
      price: 35,
      stars: 2,
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_3.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-4',
      name: 'Chloe Sofa By Domkapa 4',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_4.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-5',
      name: 'Chloe Sofa By Domkapa 5',
      category: 'sofa',
      price: 30,
      stars: 2,
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/sofa/sofa_5.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-6',
      name: 'Chloe Sofa By Domkapa 6',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/sofa/sofa_6.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-7',
      name: 'Chloe Sofa By Domkapa 7',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_7.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-8',
      name: 'Chloe Sofa By Domkapa 8',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_8.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-9',
      name: 'Chloe Sofa By Domkapa 9',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_9.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-10',
      name: 'Chloe Sofa By Domkapa 10',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_10.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-11',
      name: 'Chloe Sofa By Domkapa 11',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_11.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-12',
      name: 'Chloe Sofa By Domkapa 12',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_12.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-13',
      name: 'Chloe Sofa By Domkapa 13',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_13.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-14',
      name: 'Chloe Sofa By Domkapa 14',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_14.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-15',
      name: 'Chloe Sofa By Domkapa 15',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_15.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-16',
      name: 'Chloe Sofa By Domkapa 16',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_16.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-17',
      name: 'Chloe Sofa By Domkapa 17',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_17.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-18',
      name: 'Chloe Sofa By Domkapa 18',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_18.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-19',
      name: 'Chloe Sofa By Domkapa 19',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_19.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-20',
      name: 'Chloe Sofa By Domkapa 20',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_20.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-21',
      name: 'Chloe Sofa By Domkapa 21',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_21.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-22',
      name: 'Chloe Sofa By Domkapa 22',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_22.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-23',
      name: 'Chloe Sofa By Domkapa 23',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_23.jpeg',
    },
    {
      id: 'chloe-sofa-by-domkapa-24',
      name: 'Chloe Sofa By Domkapa 24',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/sofa/sofa_24.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-1',
      name: 'Lapiaz side table by Boca Do Lobo 1',
      category: 'table',
      price: 30,
      stars: 2,
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/table/table_1.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-2',
      name: 'Lapiaz side table by Boca Do Lobo 2',
      category: 'table',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/table/table_2.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-3',
      name: 'Lapiaz side table by Boca Do Lobo 3',
      category: 'table',
      price: 35,
      stars: 2,
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_3.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-4',
      name: 'Lapiaz side table by Boca Do Lobo 4',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_4.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-5',
      name: 'Lapiaz side table by Boca Do Lobo 5',
      category: 'table',
      price: 30,
      stars: 2,
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/table/table_5.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-6',
      name: 'Lapiaz side table by Boca Do Lobo 6',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: true,
      arrows: false,
      image: 'src=../../images/table/table_6.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-7',
      name: 'Lapiaz side table by Boca Do Lobo 7',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_7.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-8',
      name: 'Lapiaz side table by Boca Do Lobo 8',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_8.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-9',
      name: 'Lapiaz side table by Boca Do Lobo 9',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_9.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-10',
      name: 'Lapiaz side table by Boca Do Lobo 10',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_10.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-11',
      name: 'Lapiaz side table by Boca Do Lobo 11',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_11.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-12',
      name: 'Lapiaz side table by Boca Do Lobo 12',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_12.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-13',
      name: 'Lapiaz side table by Boca Do Lobo 13',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_13.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-14',
      name: 'Lapiaz side table by Boca Do Lobo 14',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_14.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-15',
      name: 'Lapiaz side table by Boca Do Lobo 15',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_15.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-16',
      name: 'Lapiaz side table by Boca Do Lobo 16',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_16.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-17',
      name: 'Lapiaz side table by Boca Do Lobo 17',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_17.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-18',
      name: 'Lapiaz side table by Boca Do Lobo 18',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_18.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-19',
      name: 'Lapiaz side table by Boca Do Lobo 19',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_19.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-20',
      name: 'Lapiaz side table by Boca Do Lobo 20',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_20.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-21',
      name: 'Lapiaz side table by Boca Do Lobo 21',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_21.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-22',
      name: 'Lapiaz side table by Boca Do Lobo 22',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_22.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-23',
      name: 'Lapiaz side table by Boca Do Lobo 23',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_23.jpeg',
    },
    {
      id: 'lapiaz-side-table-by-boca-do-lobo-24',
      name: 'Lapiaz side table by Boca Do Lobo 24',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      heart: false,
      arrows: false,
      image: 'src=../../images/table/table_24.jpeg',
    },
  ],
  cart: {
    products: [],
  },

  compare: {
    products: [],
  },

  promos: [
    {
      id: 'sale',
      rate: 0.2,
    },
  ],

  renderingModes: [
    {
      id: 'desktop',
      min: 992,
      productsPerPage: 8,
    },
    {
      id: 'tablet',
      min: 768,
      max: 991,
      productsPerPage: 3,
    },
    {
      id: 'mobile',
      max: 767,
      min: 480,
      productsPerPage: 2,
    },
    {
      id: 'extraSmall',
      max: 479,
      productsPerPage: 1,
    },
  ],
};

export default initialState;
